language: python
install:
  - pip install --upgrade pip
  - pip install poetry tox tox-travis codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov

stages:
  - lint
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-withgeoalchemy
    - stage: test
      python: 3.6
      env: TOX_ENV=py36-nogeoalchemy
    - stage: test
      python: 3.7
      env: TOX_ENV=py37-withgeoalchemy
    - stage: test
      python: pypy3
      dist: focal
      env: TOX_ENV=pypy3-withgeoalchemy
    - stage: test
      python: pypy3
      dist: focal
      env: TOX_ENV=pypy3-nogeoalchemy
    - stage: test
      python: 3.8
      env: TOX_ENV=py38-withgeoalchemy
    - stage: lint
      python: 3.6
      env: TOX_ENV=lint
    - stage: deploy
      python: 3.6
      install: true
      script: true
      after_success: true

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  provider: script
  script: poetry publish
  on:
    branch: master
    tags: true
